### ISSUE TITLE
utpm workspace link can also create symlink instead of copying

### ISSUE THREAD

**Issue by mintyfrankie** [Thumuss/utpm#26]
Hi, it's me again!

I was wondering if it's possible also to add/modify the feature of `utpm workpsace link`, making it creating symlink instead of/in addition to simply copying?

This can be also quite handy when we are developing the modules while having a test file watched by Typst (`typst watch ...`), so that updates and errors are real time instead of having to execute `utpm workspace link --force` each time.

I am not sure how other developers write their package, but for me this is quite smooth. 

Thanks!

**Comment by Thumuss** [comment]
It's a good idea but it already exist!

Using `utpm workspace link --no-copy` you can make a symlink directly inside your namespace. 

I've check early and it seems it's buggy, I'll fix it and it will be good to go!

Thank you for your time, it's always a pleasure to have a feedback!

**Comment by mintyfrankie** [comment]
Oh you are right, totally missed that. A very sweet feature :) 

A side question if I may: I see that the `utpm workspace link` function touches the cache dir instead of data dir -- for example on MacOS it's `$HOME/Library/Cache/typst/...` instead of `$HOME/Library/Application Support/typst/...`. 

When I complied my project to Typst package standard, the [official repo](https://github.com/typst/packages) encourages local testing on data dir more than the cache dir; I was wondering what your thought is on this? Will it be more standardized/less error prone to go in this way?

Thanks a lot!

**Comment by Thumuss** [comment]
> A side question if I may: I see that the `utpm workspace link` function touches the cache dir instead of data dir -- for example on MacOS it's `$HOME/Library/Cache/typst/...` instead of `$HOME/Library/Application Support/typst/...`.

It does only when the namespace is preview! Yeah it can be a bit complicated to handle it, for now I prefer editing the cache when using preview because I'm afraid that typst will intefere when using preview as a local namespace.  I need to test this a lot more but for simplicity it's better. If you need to rewrite your modification you can use `utpm ws clone -r @preview/package:X.X.X` to reset the package. 

> When I complied my project to Typst package standard, the [official repo](https://github.com/typst/packages) encourages local testing on data dir more than the cache dir; I was wondering what your thought is on this? Will it be more standardized/less error prone to go in this way?

I'll go a little deeper on that part, like I said I'm afraid that typst will interfere in the way of utpm.

Again, thanks for your feedback!

**Comment by Thumuss** [comment]
> I've checked early and it seems it's buggy, I'll fix it and it will be good to go!

It's less buggy than I expected. I tried to apply a fix, but it's already working. You just need to specify `--force` because the directory already exists in the cache directory. It's more a lack of documentation than a bug. I'll make a PR to add docs to `utpm`; for now, I'm focusing more on creating features and fixing bugs than anything else.

If you want to discuss anything in particular about `link` or something related, go ahead, or I'll close this as there is nothing to do!

**Comment by mintyfrankie** [comment]
Thanks for your prompt replies @Thumuss!

I don't know very well the Rust language, but if you would like some hands for the documentation, test cases, etc, I would be more than happy to contribute! Keep me posted.

Closing this issue for the time being as the subject was well addressed, thanks!
