### ISSUE TITLE
Confusing and verbose README. 

### ISSUE THREAD

**Issue by SylvanFranklin** [Thumuss/utpm#31]
This looks like a great project for Typst, and I would love to help out. As discussed in #30 , the gifs in the README are largely error messages, but in general I think that plain text is superior to gifts, for ease of copying and file size. This project would greatly benefit from a cleaned up README with fewer gifs and more coherent writing. I'm a native English speaker and can help out with that if you would like!

**Comment by Thumuss** [comment]
First of all, thank you! 
Yes, on #30 they mentioned gifs are wrong because I don't have prioritize the gifs. 
But I think you right, after all, plain text can be less of a pain to use and to read.
As a non-native English speaker, it takes a bit of time to make sure that my english is easily understood by non-developers and is accurate enough. If you want to translate every gif and make a proper README, I'll glad to have you on it! 

If you need any explanation, don't hesitate to ask questions, it will helps to make this project a better tool!

Thank you for your time, any help is always a pleasure <3

**Comment by SylvanFranklin** [comment]
Sick I'll hop on this ASAP!

**Comment by Thumuss** [comment]
Since #32 is merged, I'll close it for now.
If there is something to add, don't hesitate!
